---
- Red & Conectividad:
    - Router TP-Link Archer C50:
        icon: router.png
        href: http://192.168.0.1
        description: Gateway Principal y Red Dual Band

    - AdGuard Home:
        icon: adguard-home.png
        href: http://100.120.34.14:8088
        description: Servidor DNS y bloqueo de telemetría
        server: my-docker
        container: adguardhome

    - Nginx Proxy Manager:
        icon: nginx-proxy-manager.png
        href: http://100.120.34.14:81
        description: Reverse Proxy & Certificados SSL
        server: my-docker
        container: nginx-proxy-manager

- Cómputo & Servidores:
    - Proxmox VE:
        icon: proxmox.png
        href: https://100.77.123.25:8006
        description: Hipervisor de Virtualización jj

    - Portainer CE:
        icon: portainer.png
        href: http://100.120.34.14:9000
        description: Control de Contenedores NodeR
        server: my-docker
        container: portainer

    - Uptime Kuma:
        icon: uptime-kuma.png
        href: http://100.120.34.14:3001
        description: Monitor de Disponibilidad y SLAs
        server: my-docker
        container: uptime-kuma

    - Vaultwarden:
        icon: vaultwarden.png
        href: http://100.120.34.14:8080
        description: Bóveda de Contraseñas Bitwarden
        server: my-docker
        container: vaultwarden
